### PR TITLE
Make silly theme a little sillier

### PR DESCRIPTION
**Pull request by nikolas**
and fix whitespace in the css file

### CODE REVIEW

**Comment by mcfiredrill** [comment]
>> Avoid vendor prefixes.
 ???

**Comment by mcfiredrill** [comment]
how silly we talking here.....can you post a screenshot?

**Comment by nikolas** [comment]
it's really not that silly. Basically I just noticed that images on the front page weren't being rotated, so this just makes sure that they are rotated a little bit.

2017-01-27-074345_344x662_scrot

I'd like to make it a lot sillier in the future.

**Comment by mcfiredrill** [comment]
looks great ok but let's try to be a lot sillier in the future

**Comment by nikolas** [comment]
OKay

**Pull request merged**
