### PR TITLE
Make latests posts display horizontally instead of vertically

### PR DESCRIPTION
**Pull request by nikolas**
This is just an idea... I thought it looks kind of nice to fill the page
like this, let me know what you think.

2017-01-26-221551_1282x590_scrot

### CODE REVIEW

**Comment by mcfiredrill** [comment]
:cool: :cool: :cool: :cool: :cool: :cool: :cool: :cool: :cool: :cool: :cool:

**Comment by mcfiredrill** [comment]
I'm into it 👍 
OK to merge or is there any work on it left to do?

**Comment by nikolas** [comment]
OK to merge

**Comment by mcfiredrill** [comment]
thanks

**Pull request merged**
