### PR TITLE
:arrow_up: three.js r73

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by mcfiredrill** [comment]
Can we not vendor this? We should use rails-assets or bower I think.

**Comment by nikolas** [comment]
Sure... i'm not sure how to do that but I've used bower before.

**Comment by mcfiredrill** [comment]
its pretty easy, you just add the rails-assets source to the gemfile, then add the rails-assets-threejs gem to the Gemfile.
https://rails-assets.org/

**Comment by nikolas** [comment]
Alright I will do that.

Poor bower.. I wanna play mario

poor-bowser-o

**Comment by mcfiredrill** [comment]
poor bower i know :sweat:

**Comment by nikolas** [comment]
alright i changed this to use rails-assets but i'm getting this error locally: couldn't find file 'three.js' with type 'application/javascript'

**Comment by mcfiredrill** [comment]
@nikolas its probably the wrong path or filename. What I usually do is:
```
$ bundle show rails-assets-three.js
```
This will show you the path on disk, then you can find the right file to require. 
It might be just
```
*= require three
```
without the suffix, or it might be in a directory:
```
*= require somedir/three
```

**Comment by nikolas** [comment]
```
$ bundle show rails-assets-three.js
/home/nik/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rails-assets-three.js-0.72.0
```
hmm..

rails-assets.org says the path is three.js.

**Comment by nikolas** [comment]
I opened a ticket about this problem here: https://github.com/rails-assets/rails-assets/issues/303

**Comment by nikolas** [comment]
Ok.. it works when I do `require three.js.js` ...

**Comment by mcfiredrill** [comment]
Thanks!

**Pull request merged**
