### PR TITLE
Add content text to index

### LINKED ISSUE #35: [feature idea] put text along with image on front page
I know this is meant to be a clone of wakaba, but I thought it would be nice to show the text alongside the image on the frontpage aggregate for fortchan. If there's no objections I'll make a PR.

### PR DESCRIPTION
**Pull request by nikolas**
screen shot 2015-05-03 at 10 42 39 pm

Closes #35

### CODE REVIEW

**Comment by mcfiredrill** [comment]
thanks!

**Comment by mcfiredrill** [comment]
<marquee>woo</marquee>
<p>hey</p>

On Mon, May 4, 2015 at 11:43 AM, nikolas <notifications@github.com> wrote:

> nikolas wants to merge 1 commit into mcfiredrill:master from
> nikolas:add-content-to-index:
>
> [image: screen shot 2015-05-03 at 10 42 39 pm]
> <https://cloud.githubusercontent.com/assets/59292/7448360/bd1078ce-f1e5-11e4-99a4-f0b47bfe0459.png>
>
> Closes #35 <https://github.com/mcfiredrill/forttree/issues/35>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/mcfiredrill/forttree/pull/37
> Commit Summary
>
>    - Add content text to index
>
> File Changes
>
>    - *M* app/views/boards/index.html.erb
>    <https://github.com/mcfiredrill/forttree/pull/37/files#diff-0> (5)
>
> Patch Links:
>
>    - https://github.com/mcfiredrill/forttree/pull/37.patch
>    - https://github.com/mcfiredrill/forttree/pull/37.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mcfiredrill/forttree/pull/37>.
>



-- 
-Tony Miller
github.com/mcfiredrill
@freedrull
freedrool.us

**Comment by mcfiredrill** [comment]
.

On Tue, Jul 28, 2015 at 12:03 PM, Tony Miller <mcfiredrill@gmail.com> wrote:

>
>
> On Tue, Jul 28, 2015 at 12:03 PM, Tony Miller <mcfiredrill@gmail.com>
> wrote:
>
>>
>>
>> On Tue, Jul 21, 2015 at 5:05 PM, Tony Miller <mcfiredrill@gmail.com>
>> wrote:
>>
>>> <marquee>woo</marquee>
>>> <p>hey</p>
>>>
>>> On Mon, May 4, 2015 at 11:43 AM, nikolas <notifications@github.com>
>>> wrote:
>>>
>>>> nikolas wants to merge 1 commit into mcfiredrill:master from
>>>> nikolas:add-content-to-index:
>>>>
>>>> [image: screen shot 2015-05-03 at 10 42 39 pm]
>>>> <https://cloud.githubusercontent.com/assets/59292/7448360/bd1078ce-f1e5-11e4-99a4-f0b47bfe0459.png>
>>>>
>>>> Closes #35 <https://github.com/mcfiredrill/forttree/issues/35>
>>>> ------------------------------
>>>> You can view, comment on, or merge this pull request online at:
>>>>
>>>>   https://github.com/mcfiredrill/forttree/pull/37
>>>> Commit Summary
>>>>
>>>>    - Add content text to index
>>>>
>>>> File Changes
>>>>
>>>>    - *M* app/views/boards/index.html.erb
>>>>    <https://github.com/mcfiredrill/forttree/pull/37/files#diff-0> (5)
>>>>
>>>> Patch Links:
>>>>
>>>>    - https://github.com/mcfiredrill/forttree/pull/37.patch
>>>>    - https://github.com/mcfiredrill/forttree/pull/37.diff
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/mcfiredrill/forttree/pull/37>.
>>>>
>>>
>>>
>>>
>>> --
>>> -Tony Miller
>>> github.com/mcfiredrill
>>> @freedrull
>>> freedrool.us
>>>
>>
>>
>>
>> --
>> -Tony Miller
>> github.com/mcfiredrill
>> @freedrull
>> freedrool.us
>>
>
>
>
> --
> -Tony Miller
> github.com/mcfiredrill
> @freedrull
> freedrool.us
>



-- 
-Tony Miller
github.com/mcfiredrill
@freedrull
freedrool.us

**Comment by mcfiredrill** [comment]
asdf

On Tue, Jul 28, 2015 at 12:03 PM, Tony Miller <mcfiredrill@gmail.com> wrote:

> .
>
> On Tue, Jul 28, 2015 at 12:03 PM, Tony Miller <mcfiredrill@gmail.com>
> wrote:
>
>>
>>
>> On Tue, Jul 28, 2015 at 12:03 PM, Tony Miller <mcfiredrill@gmail.com>
>> wrote:
>>
>>>
>>>
>>> On Tue, Jul 21, 2015 at 5:05 PM, Tony Miller <mcfiredrill@gmail.com>
>>> wrote:
>>>
>>>> <marquee>woo</marquee>
>>>> <p>hey</p>
>>>>
>>>> On Mon, May 4, 2015 at 11:43 AM, nikolas <notifications@github.com>
>>>> wrote:
>>>>
>>>>> nikolas wants to merge 1 commit into mcfiredrill:master from
>>>>> nikolas:add-content-to-index:
>>>>>
>>>>> [image: screen shot 2015-05-03 at 10 42 39 pm]
>>>>> <https://cloud.githubusercontent.com/assets/59292/7448360/bd1078ce-f1e5-11e4-99a4-f0b47bfe0459.png>
>>>>>
>>>>> Closes #35 <https://github.com/mcfiredrill/forttree/issues/35>
>>>>> ------------------------------
>>>>> You can view, comment on, or merge this pull request online at:
>>>>>
>>>>>   https://github.com/mcfiredrill/forttree/pull/37
>>>>> Commit Summary
>>>>>
>>>>>    - Add content text to index
>>>>>
>>>>> File Changes
>>>>>
>>>>>    - *M* app/views/boards/index.html.erb
>>>>>    <https://github.com/mcfiredrill/forttree/pull/37/files#diff-0> (5)
>>>>>
>>>>> Patch Links:
>>>>>
>>>>>    - https://github.com/mcfiredrill/forttree/pull/37.patch
>>>>>    - https://github.com/mcfiredrill/forttree/pull/37.diff
>>>>>
>>>>> —
>>>>> Reply to this email directly or view it on GitHub
>>>>> <https://github.com/mcfiredrill/forttree/pull/37>.
>>>>>
>>>>
>>>>
>>>>
>>>> --
>>>> -Tony Miller
>>>> github.com/mcfiredrill
>>>> @freedrull
>>>> freedrool.us
>>>>
>>>
>>>
>>>
>>> --
>>> -Tony Miller
>>> github.com/mcfiredrill
>>> @freedrull
>>> freedrool.us
>>>
>>
>>
>>
>> --
>> -Tony Miller
>> github.com/mcfiredrill
>> @freedrull
>> freedrool.us
>>
>
>
>
> --
> -Tony Miller
> github.com/mcfiredrill
> @freedrull
> freedrool.us
>



-- 
-Tony Miller
github.com/mcfiredrill
@freedrull
freedrool.us

**Comment by mcfiredrill** [comment]
aisdjfoiajsdofijaosdifasdf

On Tue, Jul 28, 2015 at 12:04 PM, Tony Miller <mcfiredrill@gmail.com> wrote:

> asdf
>
> On Tue, Jul 28, 2015 at 12:03 PM, Tony Miller <mcfiredrill@gmail.com>
> wrote:
>
>> .
>>
>> On Tue, Jul 28, 2015 at 12:03 PM, Tony Miller <mcfiredrill@gmail.com>
>> wrote:
>>
>>>
>>>
>>> On Tue, Jul 28, 2015 at 12:03 PM, Tony Miller <mcfiredrill@gmail.com>
>>> wrote:
>>>
>>>>
>>>>
>>>> On Tue, Jul 21, 2015 at 5:05 PM, Tony Miller <mcfiredrill@gmail.com>
>>>> wrote:
>>>>
>>>>> <marquee>woo</marquee>
>>>>> <p>hey</p>
>>>>>
>>>>> On Mon, May 4, 2015 at 11:43 AM, nikolas <notifications@github.com>
>>>>> wrote:
>>>>>
>>>>>> nikolas wants to merge 1 commit into mcfiredrill:master from
>>>>>> nikolas:add-content-to-index:
>>>>>>
>>>>>> [image: screen shot 2015-05-03 at 10 42 39 pm]
>>>>>> <https://cloud.githubusercontent.com/assets/59292/7448360/bd1078ce-f1e5-11e4-99a4-f0b47bfe0459.png>
>>>>>>
>>>>>> Closes #35 <https://github.com/mcfiredrill/forttree/issues/35>
>>>>>> ------------------------------
>>>>>> You can view, comment on, or merge this pull request online at:
>>>>>>
>>>>>>   https://github.com/mcfiredrill/forttree/pull/37
>>>>>> Commit Summary
>>>>>>
>>>>>>    - Add content text to index
>>>>>>
>>>>>> File Changes
>>>>>>
>>>>>>    - *M* app/views/boards/index.html.erb
>>>>>>    <https://github.com/mcfiredrill/forttree/pull/37/files#diff-0>
>>>>>>    (5)
>>>>>>
>>>>>> Patch Links:
>>>>>>
>>>>>>    - https://github.com/mcfiredrill/forttree/pull/37.patch
>>>>>>    - https://github.com/mcfiredrill/forttree/pull/37.diff
>>>>>>
>>>>>> —
>>>>>> Reply to this email directly or view it on GitHub
>>>>>> <https://github.com/mcfiredrill/forttree/pull/37>.
>>>>>>
>>>>>
>>>>>
>>>>>
>>>>> --
>>>>> -Tony Miller
>>>>> github.com/mcfiredrill
>>>>> @freedrull
>>>>> freedrool.us
>>>>>
>>>>
>>>>
>>>>
>>>> --
>>>> -Tony Miller
>>>> github.com/mcfiredrill
>>>> @freedrull
>>>> freedrool.us
>>>>
>>>
>>>
>>>
>>> --
>>> -Tony Miller
>>> github.com/mcfiredrill
>>> @freedrull
>>> freedrool.us
>>>
>>
>>
>>
>> --
>> -Tony Miller
>> github.com/mcfiredrill
>> @freedrull
>> freedrool.us
>>
>
>
>
> --
> -Tony Miller
> github.com/mcfiredrill
> @freedrull
> freedrool.us
>



-- 
-Tony Miller
github.com/mcfiredrill
@freedrull
freedrool.us

**Comment by nikolas** [comment]
abc

**Pull request merged**
